// Package ddl parses and normalizes schema statements before they reach Burrows.
package ddl

import (
	"fmt"

	pg_query "github.com/pganalyze/pg_query_go/v6"
)

// Result describes SQL that was parsed and, when necessary, adjusted to the
// Hamstergres generated-key contract.
type Result struct {
	SQL     string
	Schema  bool
	Changed bool
}

// Normalize parses PostgreSQL SQL and rewrites generated integer columns to
// BIGINT GENERATED BY DEFAULT AS IDENTITY. BY DEFAULT lets the Proxy inject a
// fleet-wide ID while retaining durable catalog metadata on every Burrow.
func Normalize(sql string) (Result, error) {
	tree, err := pg_query.Parse(sql)
	if err != nil {
		return Result{}, fmt.Errorf("parse PostgreSQL statement: %w", err)
	}
	result := Result{SQL: sql}
	for _, raw := range tree.Stmts {
		if raw.Stmt == nil {
			continue
		}
		if create := raw.Stmt.GetCreateStmt(); create != nil {
			result.Schema = true
			for _, element := range create.TableElts {
				column := element.GetColumnDef()
				if column == nil {
					continue
				}
				serial := serialType(column.TypeName)
				identity := identityConstraint(column.Constraints)
				if serial {
					column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
					column.Constraints = append(column.Constraints, constraintNode(&pg_query.Constraint{Contype: pg_query.ConstrType_CONSTR_IDENTITY, GeneratedWhen: "d"}))
					result.Changed = true
				} else if identity != nil {
					if !bigintType(column.TypeName) {
						column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
						result.Changed = true
					}
					if identity.GeneratedWhen != "d" {
						identity.GeneratedWhen = "d"
						result.Changed = true
					}
				}
			}
		}
		if alter := raw.Stmt.GetAlterTableStmt(); alter != nil {
			result.Schema = true
			for _, commandNode := range alter.Cmds {
				command := commandNode.GetAlterTableCmd()
				if command == nil {
					continue
				}
				if command.Subtype == pg_query.AlterTableType_AT_AddColumn {
					column := command.Def.GetColumnDef()
					if column != nil {
						serial := serialType(column.TypeName)
						identity := identityConstraint(column.Constraints)
						if serial {
							column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
							column.Constraints = append(column.Constraints, constraintNode(&pg_query.Constraint{Contype: pg_query.ConstrType_CONSTR_IDENTITY, GeneratedWhen: "d"}))
							result.Changed = true
						} else if identity != nil && identity.GeneratedWhen != "d" {
							identity.GeneratedWhen = "d"
							result.Changed = true
						}
						if identity != nil && !bigintType(column.TypeName) {
							column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
							result.Changed = true
						}
					}
				}
				if command.Subtype == pg_query.AlterTableType_AT_AddIdentity {
					if constraint := command.Def.GetConstraint(); constraint != nil && constraint.GeneratedWhen != "d" {
						constraint.GeneratedWhen = "d"
						result.Changed = true
					}
				}
				if command.Subtype == pg_query.AlterTableType_AT_SetIdentity {
					for _, item := range command.Def.GetList().Items {
						if option := item.GetDefElem(); option != nil && option.Defname == "generated" {
							if value := option.Arg.GetInteger(); value != nil && value.Ival != int32('d') {
								value.Ival = int32('d')
								result.Changed = true
							}
						}
					}
				}
			}
		}
	}
	if result.Changed {
		result.SQL, err = pg_query.Deparse(tree)
		if err != nil {
			return Result{}, fmt.Errorf("deparse normalized PostgreSQL statement: %w", err)
		}
	}
	return result, nil
}

func identityConstraint(nodes []*pg_query.Node) *pg_query.Constraint {
	for _, node := range nodes {
		constraint := node.GetConstraint()
		if constraint != nil && constraint.Contype == pg_query.ConstrType_CONSTR_IDENTITY {
			return constraint
		}
	}
	return nil
}

func constraintNode(value *pg_query.Constraint) *pg_query.Node {
	return &pg_query.Node{Node: &pg_query.Node_Constraint{Constraint: value}}
}

func serialType(value *pg_query.TypeName) bool {
	name := lastTypeName(value)
	return name == "serial" || name == "serial2" || name == "serial4" || name == "serial8" || name == "smallserial" || name == "bigserial"
}

func bigintType(value *pg_query.TypeName) bool {
	name := lastTypeName(value)
	return name == "int8" || name == "bigint"
}

func lastTypeName(value *pg_query.TypeName) string {
	if value == nil || len(value.Names) == 0 {
		return ""
	}
	return value.Names[len(value.Names)-1].GetString_().Sval
}
