// SPDX-License-Identifier: AGPL-3.0-only

// Package ddl parses and normalizes schema statements before they reach Burrows.
package ddl

import (
	"fmt"

	pg_query "github.com/pganalyze/pg_query_go/v6"
)

// Result describes SQL that was parsed and, when necessary, adjusted to the
// Hamstergres generated-key contract.
type Result struct {
	SQL     string
	Schema  bool
	Changed bool
}

// Normalize parses PostgreSQL SQL and rewrites generated integer columns to
// BIGINT GENERATED BY DEFAULT AS IDENTITY. BY DEFAULT lets the Proxy inject a
// fleet-wide ID while retaining durable catalog metadata on every Burrow.
func Normalize(sql string) (Result, error) {
	tree, err := pg_query.Parse(sql)
	if err != nil {
		return Result{}, fmt.Errorf("parse PostgreSQL statement: %w", err)
	}
	result := Result{SQL: sql}
	for _, raw := range tree.Stmts {
		if raw.Stmt == nil {
			continue
		}
		if create := raw.Stmt.GetCreateStmt(); create != nil {
			result.Schema = true
			for _, element := range create.TableElts {
				if normalizeColumnDefinition(element.GetColumnDef()) {
					result.Changed = true
				}
			}
		}
		if alter := raw.Stmt.GetAlterTableStmt(); alter != nil {
			result.Schema = true
			for _, commandNode := range alter.Cmds {
				command := commandNode.GetAlterTableCmd()
				if command == nil {
					continue
				}
				if command.Subtype == pg_query.AlterTableType_AT_AddColumn {
					if normalizeColumnDefinition(command.Def.GetColumnDef()) {
						result.Changed = true
					}
				}
				if command.Subtype == pg_query.AlterTableType_AT_AddIdentity {
					if constraint := command.Def.GetConstraint(); constraint != nil && constraint.GeneratedWhen != "d" {
						constraint.GeneratedWhen = "d"
						result.Changed = true
					}
				}
				if command.Subtype == pg_query.AlterTableType_AT_SetIdentity {
					options := command.Def.GetList()
					if options == nil {
						continue
					}
					for _, item := range options.Items {
						if option := item.GetDefElem(); option != nil && option.Defname == "generated" {
							if value := option.Arg.GetInteger(); value != nil && value.Ival != int32('d') {
								value.Ival = int32('d')
								result.Changed = true
							}
						}
					}
				}
			}
		}
	}
	if result.Changed {
		result.SQL, err = pg_query.Deparse(tree)
		if err != nil {
			return Result{}, fmt.Errorf("deparse normalized PostgreSQL statement: %w", err)
		}
	}
	return result, nil
}

// normalizeColumnDefinition rewrites an ordinary, self-contained column
// definition to the Hamstergres generated-key contract. PostgreSQL also uses
// ColumnDef for typed-table and partition column options. Those nodes inherit
// their type from another relation and deliberately have a nil TypeName. Leave
// them unchanged so PostgreSQL can return its native unsupported-shape error.
func normalizeColumnDefinition(column *pg_query.ColumnDef) bool {
	if column == nil || column.TypeName == nil {
		return false
	}

	identity := identityConstraint(column.Constraints)
	if serialType(column.TypeName) {
		column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
		column.Constraints = append(column.Constraints, constraintNode(&pg_query.Constraint{Contype: pg_query.ConstrType_CONSTR_IDENTITY, GeneratedWhen: "d"}))
		return true
	}
	if identity == nil {
		return false
	}

	changed := false
	if !bigintType(column.TypeName) {
		column.TypeName.Names = []*pg_query.Node{pg_query.MakeStrNode("pg_catalog"), pg_query.MakeStrNode("int8")}
		changed = true
	}
	if identity.GeneratedWhen != "d" {
		identity.GeneratedWhen = "d"
		changed = true
	}
	return changed
}

func identityConstraint(nodes []*pg_query.Node) *pg_query.Constraint {
	for _, node := range nodes {
		if node == nil {
			continue
		}
		constraint := node.GetConstraint()
		if constraint != nil && constraint.Contype == pg_query.ConstrType_CONSTR_IDENTITY {
			return constraint
		}
	}
	return nil
}

func constraintNode(value *pg_query.Constraint) *pg_query.Node {
	return &pg_query.Node{Node: &pg_query.Node_Constraint{Constraint: value}}
}

func serialType(value *pg_query.TypeName) bool {
	name := lastTypeName(value)
	return name == "serial" || name == "serial2" || name == "serial4" || name == "serial8" || name == "smallserial" || name == "bigserial"
}

func bigintType(value *pg_query.TypeName) bool {
	name := lastTypeName(value)
	return name == "int8" || name == "bigint"
}

func lastTypeName(value *pg_query.TypeName) string {
	if value == nil || len(value.Names) == 0 {
		return ""
	}
	last := value.Names[len(value.Names)-1]
	if last == nil {
		return ""
	}
	name := last.GetString_()
	if name == nil {
		return ""
	}
	return name.Sval
}
