// SPDX-License-Identifier: AGPL-3.0-only

package ddl

import (
	"strings"
	"testing"
)

func TestNormalizeCreateTableGeneratedKeys(t *testing.T) {
	for _, sql := range []string{
		"CREATE TABLE users (id serial PRIMARY KEY, name text)",
		"CREATE TABLE users (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name text)",
	} {
		result, err := Normalize(sql)
		if err != nil {
			t.Fatal(err)
		}
		if !result.Schema || !result.Changed {
			t.Fatalf("Normalize(%q) = %#v", sql, result)
		}
		upper := strings.ToUpper(result.SQL)
		if !strings.Contains(upper, "BIGINT") || !strings.Contains(upper, "GENERATED BY DEFAULT AS IDENTITY") || strings.Contains(upper, "GENERATED ALWAYS") {
			t.Fatalf("normalized SQL = %q", result.SQL)
		}
	}
}

func TestNormalizePgDumpIdentityAlter(t *testing.T) {
	sql := `ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.users_id_seq START WITH 12)`
	result, err := Normalize(sql)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed || !strings.Contains(strings.ToUpper(result.SQL), "ADD GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("Normalize = %#v", result)
	}
}

func TestNormalizePgDumpSchemaShape(t *testing.T) {
	sql := `CREATE TABLE public.users (id bigint NOT NULL, name text);
ALTER TABLE ONLY public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);`
	result, err := Normalize(sql)
	if err != nil {
		t.Fatal(err)
	}
	upper := strings.ToUpper(result.SQL)
	if !result.Schema || !result.Changed || strings.Contains(upper, "GENERATED ALWAYS") || !strings.Contains(upper, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("Normalize pg_dump schema = %#v", result)
	}
}

func TestNormalizeAlterSetGeneratedAlways(t *testing.T) {
	result, err := Normalize("ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Changed || strings.Contains(strings.ToUpper(result.SQL), "GENERATED ALWAYS") || !strings.Contains(strings.ToUpper(result.SQL), "GENERATED BY DEFAULT") {
		t.Fatalf("Normalize = %#v", result)
	}
}

func TestNormalizePreservesOrdinaryStatements(t *testing.T) {
	sql := "ALTER TABLE users ADD COLUMN name text"
	result, err := Normalize(sql)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Schema || result.Changed || result.SQL != sql {
		t.Fatalf("Normalize = %#v", result)
	}
}

func TestNormalizePreservesInheritedColumnIdentityErrors(t *testing.T) {
	for _, sql := range []string{
		"CREATE TABLE itest12 OF itest_type (f1 WITH OPTIONS GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE pitest1_pfail PARTITION OF pitest1 (f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY) FOR VALUES FROM ('2016-11-01') TO ('2016-12-01')",
	} {
		result, err := Normalize(sql)
		if err != nil {
			t.Fatalf("Normalize(%q): %v", sql, err)
		}
		if !result.Schema || result.Changed || result.SQL != sql {
			t.Fatalf("Normalize(%q) = %#v", sql, result)
		}
	}
}

func FuzzNormalizeDDLNeverPanics(f *testing.F) {
	for _, sql := range []string{
		"CREATE TABLE users (id serial PRIMARY KEY, name text)",
		"CREATE TABLE itest12 OF itest_type (f1 WITH OPTIONS GENERATED ALWAYS AS IDENTITY)",
		"CREATE TABLE pitest1_pfail PARTITION OF pitest1 (f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY) FOR VALUES FROM ('2016-11-01') TO ('2016-12-01')",
		"ALTER TABLE users ADD COLUMN id bigint GENERATED ALWAYS AS IDENTITY",
		"ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS",
	} {
		f.Add(sql)
	}

	f.Fuzz(func(t *testing.T, sql string) {
		_, _ = Normalize(sql)
	})
}
